config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#index'
  get 'user_sessions/new'
  get 'user_sessions/create'
  get 'user_sessions/destroy'
  resources :records
  resources :users
  resources :user_sessions
  get 'help' => 'help#help', :as => :help
  post 'send_mail' => 'users#send_mail'
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/record.rb
class Record < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  validates :password, length: { minimum: 3 }, on: :create
  validates :password, confirmation: true, on: :create
  validates :password_confirmation, presence: true, on: :create
  validates :email, uniqueness: true, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :require_login
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  private
  def not_authenticated
    redirect_to login_path, alert: "サービス利用のためにはログインしてください"
  end
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
  skip_before_filter :require_login
  def help

  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  # GET /records
  # GET /records.json
  def index
    @records = Record.all
  end

  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:sender_id, :receiver_id)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(:users, notice: 'ログインに成功しました')
    else
      flash.now[:alert] = 'ログインに失敗しました'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'ログアウトしました')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_login, only: [:new, :create]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Dancer was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def send_mail
    logger.debug("[USER CTR]<send_mail> fire")
    users = params[:users]
    logger.debug("[USER CTR]<send_mail> users: #{users} ")
    logger.debug("[USER CTR]<send_mail> メールを送ります. ")
    users.each do |u|
      if u.length == 2 then
        @user = User.find(u[:id])
        logger.debug("[USER CTR]<send_mail> @user.count: #{@user.count} ")
        logger.debug("[USER CTR]<send_mail> @user.id: #{@user.id} ")
        count = User.find(@user.id).count
        logger.debug("[USER CTR]<send_mail> count: #{count} ")
        if count == nil then
          logger.debug("[USER CTR]<send_mail> カウント初期化")
          count = 0
        end
        count = count + 1
        @user.update(count: count)
        logger.debug("[USER CTR]<send_mail> @user.count: #{@user.count} ")
        logger.debug("[USER CTR]<send_mail> @user_id: #{@user.id}")
        UserMailer.post_email(@user).deliver_now
      end
    end
    respond_to do |format|
        format.html { redirect_to users_path, notice: 'メールが送信されました' }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :sex, :age, :image, :introduction, :count, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/help/help.html.erb
<div class="container">
  <h1 class="text-center">ヘルプ</h1>
  <h2>ログイン</h2>
  <p>
    ログインしないと, サービスの機能が使えません. ログインできるアカウントをお持ちでない方は, まずアカウントをお作りください.
  </p>
  <h2>アカウント作成</h2>
  <p>
    画面上部ヘッダーのメニューバーから[新規ユーザー登録]を選択してください. そして名前, メールアドレス, パスワード, 確認用パスワードを打ち込んでください. パスワード, 確認用パスワードは全てメールアドレスに統一することを, セキュリティ的にもオススメします.
  </p>
  <h2>ログイン</h2>
  <p>
    先ほど作ったアドレスとパスワードでログインしてください.
  </p>
  <h2>ログイン後</h2>
  <p>
    ログイン後は, メニューバーにあるユーザー選択を選択してください. そうするとユーザー一覧が出ます. そのユーザーにチェックを入れると, その人に通知を送ることができます. またメニューからユーザー情報を変更できます. 万が一名前やアドレスを間違えた場合はそちらから修正してください.
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShyqueueServer</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- モバイル表示用の省略メニュー -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle"
                data-toggle="collapse" data-target="#navbar-menu">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "ShyQueue", users_path, :method=> :get, :class => "navbar-brand" %>
            </div>
            <!-- ナビゲーションメニュー -->
            <div class="collapse navbar-collapse" id="navbar-menu">
                <!-- <form class="navbar-form navbar-right hidden-lg">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="キーワード">
                    </div>
                    <button type="submit" class="btn btn-info">ユーザー名検索</button>
                </form> -->
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <!-- <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            アカウント情報<span class="caret"></span>
                        </a> -->
                        <ul class="dropdown-toggle" data-toggle="dropdown" role="menu">
                          <% if current_user %>
                          <li>
                            <%= link_to "ユーザー選択", users_path, :method=> :get %>
                          </li>
                            <li>
                              <%= link_to "ユーザー情報修正", edit_user_path(current_user.id), :method=> :get %>
                            </li>
                            <li>
                              <%= link_to "ログアウト", :logout, :method=> :post  %>
                            </li>
                            <li>
                              <%= link_to "ヘルプ", '/help', :method=> :get %>
                            </li>
                          <% else %>
                            <li>
                              <%= link_to "新規ユーザー登録", new_user_path, :method=> :get %>
                            </li>
                            <li>
                              <%= link_to "ログイン", :login, :method=> :get %>
                            </li>
                            <li>
                              <%= link_to "ヘルプ", '/help', :method=> :get %>
                            </li>
                          <% end %>
                        </ul>
                    </li>
                <ul>
            </div>
        </div>
    </nav>

    <div>
      <p id="notice"><%= flash[:notice] %></p>
      <p id="alert"><%= flash[:alert] %></p>
    </div>
    <%= yield %>

</body>
</html>

app/views/records/_form.html.erb
<%= form_for(@record) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sender_id %><br>
    <%= f.number_field :sender_id %>
  </div>
  <div class="field">
    <%= f.label :receiver_id %><br>
    <%= f.number_field :receiver_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing Record</h1>

<%= render 'form' %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Records</h1>

<table>
  <thead>
    <tr>
      <th>Sender</th>
      <th>Receiver</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.sender_id %></td>
        <td><%= record.receiver_id %></td>
        <td><%= link_to 'Show', record %></td>
        <td><%= link_to 'Edit', edit_record_path(record) %></td>
        <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Record', new_record_path %>

app/views/records/new.html.erb
<h1>New Record</h1>

<%= render 'form' %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sender:</strong>
  <%= @record.sender_id %>
</p>

<p>
  <strong>Receiver:</strong>
  <%= @record.receiver_id %>
</p>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>

app/views/user_sessions/_form.html.erb
<div class="container">
<%= form_tag(user_sessions_path, :method => :post, :class => "form-group") do %>
  <div class="field form-group">
    <%= label_tag :email, "メールアドレス" %><br/>
    <%= text_field_tag :email, nil,class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= label_tag :password, "パスワード" %><br/>
    <%= password_field_tag :password, nil,class: 'form-control' %>
  </div>
  <div class="actions">
    <%= submit_tag "ログイン", class: "btn btn-lg btn-info col-xs-6 text-center col-xs-offset-3" %>
  </div>
<% end %>
</div>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1 class="text-center">ログイン</h1>

<%= render 'form' %>

app/views/users/_form.html.erb
<%= form_for(@user, :html => {class: 'center-block container'}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name, "名前" %><br>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :email, "メールアドレス" %><br>
    <%= f.text_field :email, :class => "form-control" %>
  </div>
  <div class="field form-group">
   <%= f.label :password, "パスワード" %><br />
   <%= f.password_field :password, :class => "form-control" %>
</div>
<div class="field form-group">
   <%= f.label :password_confirmation, "確認用パスワード" %><br />
   <%= f.password_field :password_confirmation, :class => "form-control" %>
</div>
  <div class="actions">
    <%= f.submit "送信", class: "btn btn-lg btn-info col-xs-6 text-center col-xs-offset-3" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザー情報修正</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center">参加者一覧</h1>

<%= form_tag("/send_mail", method: "post", class: "form-group form-group-lg") do %>
<table class="table">
  <thead>
    <tr>
      <th class='col-xs-6 label_text'>宛先</th>
      <th class='col-xs-6 label_text'>名前</th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
  <tr>
    <%= hidden_field_tag 'users[][id]', user.id %>
      <td>  <%= check_box_tag 'users[][user]', nil %></td>
      <td>  <%= label_tag user.name, nil, {class: 'label_text'} %></td>
  </tr>
  <% end %>
</tbody>
</table>
</div>
  <%= submit_tag "送信", :class => "btn btn-lg btn-info col-xs-6 text-center col-xs-offset-3" %>


<% end %>

app/views/users/new.html.erb
<h1 class="text-center">参加者登録</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>